ai_api_key: ""
log_level: "info"

kafka_brokers: ["kafka:9092"]
kafka_consumer_client_id: request-consumer-1
kafka_consumer_group_id: request-consumer-group
kafka_consumer_topics: ["request"]
kafka_producer_client_id: response-producer-1
kafka_producer_topics: ["response"]
log_kafka_topics: ["logs"]

pg_user: postgres
pg_password: postgres
pg_host: "postgres"
pg_port: 5432
pg_database: "storage"